//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3634
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderDish.Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Chinese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Chinese() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderDish.Resources.Chinese", typeof(Chinese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 购买 的本地化字符串。
        /// </summary>
        internal static string abtnBuy {
            get {
                return ResourceManager.GetString("abtnBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string btnReturn {
            get {
                return ResourceManager.GetString("btnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清单列表 的本地化字符串。
        /// </summary>
        internal static string labelTitle {
            get {
                return ResourceManager.GetString("labelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string ListForm_abpActionBar_abtn {
            get {
                return ResourceManager.GetString("ListForm_abpActionBar_abtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买 的本地化字符串。
        /// </summary>
        internal static string ListForm_pspFoodShow_btnBuy {
            get {
                return ResourceManager.GetString("ListForm_pspFoodShow_btnBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一个 的本地化字符串。
        /// </summary>
        internal static string ListForm_pspFoodShow_btnLast {
            get {
                return ResourceManager.GetString("ListForm_pspFoodShow_btnLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一个 的本地化字符串。
        /// </summary>
        internal static string ListForm_pspFoodShow_btnNext {
            get {
                return ResourceManager.GetString("ListForm_pspFoodShow_btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜名 的本地化字符串。
        /// </summary>
        internal static string LV_FN {
            get {
                return ResourceManager.GetString("LV_FN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格 的本地化字符串。
        /// </summary>
        internal static string LV_PR {
            get {
                return ResourceManager.GetString("LV_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 份数 的本地化字符串。
        /// </summary>
        internal static string LV_QU {
            get {
                return ResourceManager.GetString("LV_QU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计 的本地化字符串。
        /// </summary>
        internal static string LV_TO {
            get {
                return ResourceManager.GetString("LV_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口味备注 的本地化字符串。
        /// </summary>
        internal static string LV_TR {
            get {
                return ResourceManager.GetString("LV_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string MainForm_btnExit {
            get {
                return ResourceManager.GetString("MainForm_btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点菜列表 的本地化字符串。
        /// </summary>
        internal static string MainForm_btnList {
            get {
                return ResourceManager.GetString("MainForm_btnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看订单 的本地化字符串。
        /// </summary>
        internal static string MainForm_btnOrder {
            get {
                return ResourceManager.GetString("MainForm_btnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加订单: 的本地化字符串。
        /// </summary>
        internal static string MSGBOX_Add {
            get {
                return ResourceManager.GetString("MSGBOX_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在订单： 的本地化字符串。
        /// </summary>
        internal static string MSGBOX_Exist {
            get {
                return ResourceManager.GetString("MSGBOX_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单提交失败! 的本地化字符串。
        /// </summary>
        internal static string MSGBOX_Fail {
            get {
                return ResourceManager.GetString("MSGBOX_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化失败! 的本地化字符串。
        /// </summary>
        internal static string MSGBOX_InitFail {
            get {
                return ResourceManager.GetString("MSGBOX_InitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单提交成功! 的本地化字符串。
        /// </summary>
        internal static string MSGBOX_Succ {
            get {
                return ResourceManager.GetString("MSGBOX_Succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string OD_Del {
            get {
                return ResourceManager.GetString("OD_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改数量 的本地化字符串。
        /// </summary>
        internal static string OD_ModCount {
            get {
                return ResourceManager.GetString("OD_ModCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口味备注 的本地化字符串。
        /// </summary>
        internal static string OD_Remark {
            get {
                return ResourceManager.GetString("OD_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请联系管理员！ 的本地化字符串。
        /// </summary>
        internal static string OrderComplete {
            get {
                return ResourceManager.GetString("OrderComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string RemarkSettingForm_btnCancel {
            get {
                return ResourceManager.GetString("RemarkSettingForm_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string RemarkSettingForm_btnSave {
            get {
                return ResourceManager.GetString("RemarkSettingForm_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口味需求: 的本地化字符串。
        /// </summary>
        internal static string RemarkSettingForm_laber {
            get {
                return ResourceManager.GetString("RemarkSettingForm_laber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string ReportForm_btnReflash {
            get {
                return ResourceManager.GetString("ReportForm_btnReflash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string ReportForm_btnReturn {
            get {
                return ResourceManager.GetString("ReportForm_btnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        internal static string ReportForm_btnSubmit {
            get {
                return ResourceManager.GetString("ReportForm_btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一次只能修改一行! 的本地化字符串。
        /// </summary>
        internal static string ReportForm_Faile1 {
            get {
                return ResourceManager.GetString("ReportForm_Faile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取订单失败! 的本地化字符串。
        /// </summary>
        internal static string ReportForm_Faile2 {
            get {
                return ResourceManager.GetString("ReportForm_Faile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要修改的行! 的本地化字符串。
        /// </summary>
        internal static string ReportForm_Faile3 {
            get {
                return ResourceManager.GetString("ReportForm_Faile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜名 的本地化字符串。
        /// </summary>
        internal static string ReportForm_LV1 {
            get {
                return ResourceManager.GetString("ReportForm_LV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格 的本地化字符串。
        /// </summary>
        internal static string ReportForm_LV2 {
            get {
                return ResourceManager.GetString("ReportForm_LV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 份数 的本地化字符串。
        /// </summary>
        internal static string ReportForm_LV3 {
            get {
                return ResourceManager.GetString("ReportForm_LV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口味备注 的本地化字符串。
        /// </summary>
        internal static string ReportForm_LV4 {
            get {
                return ResourceManager.GetString("ReportForm_LV4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单状态 的本地化字符串。
        /// </summary>
        internal static string ReportForm_LV5 {
            get {
                return ResourceManager.GetString("ReportForm_LV5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单列表为空! 的本地化字符串。
        /// </summary>
        internal static string ReportForm_None {
            get {
                return ResourceManager.GetString("ReportForm_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单已提交! 的本地化字符串。
        /// </summary>
        internal static string ReportForm_OK {
            get {
                return ResourceManager.GetString("ReportForm_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源准备中... 的本地化字符串。
        /// </summary>
        internal static string WaittingFrom_strMsg {
            get {
                return ResourceManager.GetString("WaittingFrom_strMsg", resourceCulture);
            }
        }
    }
}
