//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3634
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderDish.Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal English() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderDish.Resources.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Buy 的本地化字符串。
        /// </summary>
        internal static string abtnBuy {
            get {
                return ResourceManager.GetString("abtnBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        internal static string btnReturn {
            get {
                return ResourceManager.GetString("btnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderList 的本地化字符串。
        /// </summary>
        internal static string labelTitle {
            get {
                return ResourceManager.GetString("labelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        internal static string ListForm_abpActionBar_abtn {
            get {
                return ResourceManager.GetString("ListForm_abpActionBar_abtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buy 的本地化字符串。
        /// </summary>
        internal static string ListForm_pspFoodShow_btnBuy {
            get {
                return ResourceManager.GetString("ListForm_pspFoodShow_btnBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        internal static string ListForm_pspFoodShow_btnLast {
            get {
                return ResourceManager.GetString("ListForm_pspFoodShow_btnLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string ListForm_pspFoodShow_btnNext {
            get {
                return ResourceManager.GetString("ListForm_pspFoodShow_btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Food Name 的本地化字符串。
        /// </summary>
        internal static string LV_FN {
            get {
                return ResourceManager.GetString("LV_FN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price 的本地化字符串。
        /// </summary>
        internal static string LV_PR {
            get {
                return ResourceManager.GetString("LV_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quantity 的本地化字符串。
        /// </summary>
        internal static string LV_QU {
            get {
                return ResourceManager.GetString("LV_QU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        internal static string LV_TO {
            get {
                return ResourceManager.GetString("LV_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Taste Remark 的本地化字符串。
        /// </summary>
        internal static string LV_TR {
            get {
                return ResourceManager.GetString("LV_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string MainForm_btnExit {
            get {
                return ResourceManager.GetString("MainForm_btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetFood 的本地化字符串。
        /// </summary>
        internal static string MainForm_btnList {
            get {
                return ResourceManager.GetString("MainForm_btnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowOrder 的本地化字符串。
        /// </summary>
        internal static string MainForm_btnOrder {
            get {
                return ResourceManager.GetString("MainForm_btnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to list: 的本地化字符串。
        /// </summary>
        internal static string MSGBOX_Add {
            get {
                return ResourceManager.GetString("MSGBOX_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Had exist: 的本地化字符串。
        /// </summary>
        internal static string MSGBOX_Exist {
            get {
                return ResourceManager.GetString("MSGBOX_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Faile! 的本地化字符串。
        /// </summary>
        internal static string MSGBOX_Fail {
            get {
                return ResourceManager.GetString("MSGBOX_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Init Fail! 的本地化字符串。
        /// </summary>
        internal static string MSGBOX_InitFail {
            get {
                return ResourceManager.GetString("MSGBOX_InitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success! 的本地化字符串。
        /// </summary>
        internal static string MSGBOX_Succ {
            get {
                return ResourceManager.GetString("MSGBOX_Succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string OD_Del {
            get {
                return ResourceManager.GetString("OD_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Amount 的本地化字符串。
        /// </summary>
        internal static string OD_ModCount {
            get {
                return ResourceManager.GetString("OD_ModCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Taste setting 的本地化字符串。
        /// </summary>
        internal static string OD_Remark {
            get {
                return ResourceManager.GetString("OD_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please contact to Admin! 的本地化字符串。
        /// </summary>
        internal static string OrderComplete {
            get {
                return ResourceManager.GetString("OrderComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string RemarkSettingForm_btnCancel {
            get {
                return ResourceManager.GetString("RemarkSettingForm_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string RemarkSettingForm_btnSave {
            get {
                return ResourceManager.GetString("RemarkSettingForm_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Taste Needed: 的本地化字符串。
        /// </summary>
        internal static string RemarkSettingForm_laber {
            get {
                return ResourceManager.GetString("RemarkSettingForm_laber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reflash 的本地化字符串。
        /// </summary>
        internal static string ReportForm_btnReflash {
            get {
                return ResourceManager.GetString("ReportForm_btnReflash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        internal static string ReportForm_btnReturn {
            get {
                return ResourceManager.GetString("ReportForm_btnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string ReportForm_btnSubmit {
            get {
                return ResourceManager.GetString("ReportForm_btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Once modify a row! 的本地化字符串。
        /// </summary>
        internal static string ReportForm_Faile1 {
            get {
                return ResourceManager.GetString("ReportForm_Faile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to get order! 的本地化字符串。
        /// </summary>
        internal static string ReportForm_Faile2 {
            get {
                return ResourceManager.GetString("ReportForm_Faile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the row need modify! 的本地化字符串。
        /// </summary>
        internal static string ReportForm_Faile3 {
            get {
                return ResourceManager.GetString("ReportForm_Faile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Food Name 的本地化字符串。
        /// </summary>
        internal static string ReportForm_LV1 {
            get {
                return ResourceManager.GetString("ReportForm_LV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price 的本地化字符串。
        /// </summary>
        internal static string ReportForm_LV2 {
            get {
                return ResourceManager.GetString("ReportForm_LV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quantity 的本地化字符串。
        /// </summary>
        internal static string ReportForm_LV3 {
            get {
                return ResourceManager.GetString("ReportForm_LV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TasteRemark 的本地化字符串。
        /// </summary>
        internal static string ReportForm_LV4 {
            get {
                return ResourceManager.GetString("ReportForm_LV4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderState 的本地化字符串。
        /// </summary>
        internal static string ReportForm_LV5 {
            get {
                return ResourceManager.GetString("ReportForm_LV5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None! 的本地化字符串。
        /// </summary>
        internal static string ReportForm_None {
            get {
                return ResourceManager.GetString("ReportForm_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order had submitted! 的本地化字符串。
        /// </summary>
        internal static string ReportForm_OK {
            get {
                return ResourceManager.GetString("ReportForm_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please waitting... 的本地化字符串。
        /// </summary>
        internal static string WaittingFrom_strMsg {
            get {
                return ResourceManager.GetString("WaittingFrom_strMsg", resourceCulture);
            }
        }
    }
}
